apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadxylb9196-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadxylb9196-tenant-component
    app.kubernetes.io/part-of: loadxylb9196-tenant-app
  name: loadxylb9196-tenant-component
  namespace: loadxylb9196-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadxylb9196-tenant-component
    weight: null
status: {}
